POST http://localhost:5000/users
Content-Type: application/json

{
  name: "Rafael III",
  emai: "rflprdnt@gmail.com",
  password: "rappy",
  confPassword: "rappy"
  role: "admin"

}



//update users   (code after "user/" needed)
PATCH http://localhost:5000/users/
Content-Type: application/json

{
  name: "Rafael III Updated",
  emai: "rflprdnt@gmail.com",
  password: "",
  confPassword: ""
  role: "admin"

}


//delete user (code after "user/" needed)
DELETE http://localhost:5000/users/