POST ht tp://localhost:5000/users
Content-Type: application/json

{
  name: "Rafael III",
  emai: "rflprdnt@gmail.com",
  password: "rappy",
  confPassword: "rappy"
  role: "admin"
}

###'
GET http://localhost:5000

###
//update users   (code after "user/" needed)
PATCH http://localhost:5000/users/
Content-Type: application/json

{
  name: "Rafael III Updated",
  emai: "rflprdnt@gmail.com",
  password: "",
  confPassword: ""
  role: "admin"

}

###
//Login User
POST http://localhost:5000/login
Content-Type: : application/json

{
  email: "admin@gmial.com",
  password: "123456"
}

###
POST http://localhost:5000/login
Content-Type: : application/json

{
  email: "john@gmial.com",
  password: "123456"
}

###
//delete user (code after "user/" needed)
DELETE http://localhost:5000/users/
